import React from 'react';
import { Gift, Loader2, Copy, BadgePercent } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/src/shared/ui/button';
import { Card } from '@/src/shared/ui/card';
import { useVouchers } from '@/src/entities/user/api/user-api';
const formatMoney = (value?: number | null) => Number(value || 0).toLocaleString('vi-VN') + ' ₫';
const formatDate = (value?: string | Date | null) => value ? new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date(value)) : 'Không giới hạn';
const discountLabel = (voucher: any) => voucher.type === 'PERCENT' ? `Giảm ${voucher.value}%` : `Giảm ${formatMoney(voucher.value)}`;
export const VouchersTab: React.FC = () => {
  const { data: vouchers = [], isLoading } = useVouchers();
  const copyCode = async (code: string) => { await navigator.clipboard.writeText(code); toast.success(`Đã copy mã ${code}`); };
  if (isLoading) return <div className="flex min-h-[360px] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 border-b border-border/50 pb-6 md:flex-row md:items-center"><div><h2 className="font-sans text-2xl font-black uppercase italic tracking-tight">Voucher của tôi</h2><p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground opacity-70">Ưu đãi đang có thể dùng cho tài khoản này</p></div><div className="flex items-center gap-2 rounded-2xl border border-primary/10 bg-primary/5 px-4 py-2"><Gift className="h-4 w-4 text-primary" /><span className="text-xs font-black text-primary">{vouchers.length} voucher</span></div></div>{vouchers.length ? <div className="grid gap-4 md:grid-cols-2">{vouchers.map((voucher: any) => <Card key={voucher.id} className="overflow-hidden border border-border/60 bg-card shadow-soft"><div className="flex min-h-36"><div className="flex w-28 shrink-0 items-center justify-center bg-primary text-primary-foreground"><BadgePercent className="h-10 w-10" /></div><div className="min-w-0 flex-1 space-y-3 p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-widest text-primary">{discountLabel(voucher)}</p><h3 className="mt-1 line-clamp-2 text-base font-black">{voucher.title}</h3></div><Button variant="outline" size="sm" className="h-9 shrink-0 rounded-xl text-[10px] font-black uppercase" onClick={() => copyCode(voucher.code)}><Copy className="mr-1 h-3.5 w-3.5" /> Copy</Button></div>{voucher.description && <p className="line-clamp-2 text-sm text-muted-foreground">{voucher.description}</p>}<div className="flex flex-wrap gap-2 text-[11px] font-bold text-muted-foreground"><span className="rounded-lg bg-muted/40 px-2.5 py-1">Mã: <b className="text-foreground">{voucher.code}</b></span><span className="rounded-lg bg-muted/40 px-2.5 py-1">Tối thiểu: {formatMoney(voucher.minOrderValue)}</span><span className="rounded-lg bg-muted/40 px-2.5 py-1">HSD: {formatDate(voucher.endsAt)}</span></div></div></div></Card>)}</div> : <div className="rounded-[32px] border border-dashed border-border/60 bg-card/60 px-6 py-16 text-center"><Gift className="mx-auto mb-4 h-12 w-12 text-muted-foreground/40" /><h3 className="text-lg font-black uppercase italic">Chưa có voucher khả dụng</h3><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">Khi cửa hàng phát hành voucher mới, bạn sẽ thấy mã ưu đãi tại đây.</p></div>}</div>;
};
